# Generated by Django 4.1.5 on 2023-01-25 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateField(default=datetime.time(8, 40, 19, 100673)),
        ),
    ]
