# Generated by Django 4.1.5 on 2023-01-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ratings_profile_rating_tag_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='rating',
        ),
    ]
