# Generated by Django 4.1.3 on 2022-12-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_question_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
