# Generated by Django 4.1.5 on 2023-01-24 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_profile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateField(default=datetime.time(15, 52, 0, 543270)),
        ),
    ]
