# Generated by Django 4.1.3 on 2023-01-05 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
