# Generated by Django 4.1.3 on 2023-01-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/avatar-1.png', upload_to='avatar/img/%Y/%m/%d/'),
        ),
    ]
