# Generated by Django 4.1.3 on 2023-01-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/img/avatar-1.png', upload_to='avatar/img/%Y/%m/%d/'),
        ),
    ]
